# Generated by Django 5.1.3 on 2024-12-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_useraccount_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_img_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
